replicaCount: 2

image:
  repository: nginx
  tag: "1.27.3-alpine3.20"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

backendUrl: "http://backend:5000"

resources:
  requests:
    cpu: "20m"
    memory: "32Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"

probes:
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5
