apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword }}
  MYSQL_DATABASE: {{ .Values.auth.database }}
  MYSQL_USER: {{ .Values.auth.user }}
  MYSQL_PASSWORD: {{ .Values.auth.password }}
