apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  root-password: {{ .Values.auth.rootPassword }}
  username: {{ .Values.auth.user }}
  password: {{ .Values.auth.password }}
