image:
  repository: mysql
  tag: "8.0.40"
  pullPolicy: IfNotPresent

auth:
  rootPassword: ""
  database: "tododb"
  user: "todouser"
  password: ""

persistence:
  size: 1Gi
  storageClass: "local-path"

service:
  type: ClusterIP
  port: 3306

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
