schedule: "0 2 * * *"

image:
  repository: mysql
  tag: "8.0"

mysql:
  host: "mysql"
  secretName: "mysql-secret"
  passwordKey: "mysql-root-password"
  databaseKey: "mysql-database"

persistence:
  size: 2Gi
  storageClass: "local-path"

retentionDays: 7
